require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'gem_comet.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 4
